name: 'Install Flutter SDK'
description: 'Dart and Flutter CLIs available for your GitHub Action'
author: 'Marcin Wróblewski, Monterail Sp. z o.o. (monterail.com)'
branding:
  color: 'white'
  icon: 'download'
inputs:
  channel:
    description: 'Desired Flutter channel'
    required: false
    default: 'stable'
  precache:
    description: 'Comma-separated platforms list to precache'
    required: false
    default: 'no'
runs:
  using: 'composite'
  steps:
    - run: chmod +x $GITHUB_ACTION_PATH/install-flutter-sdk.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/install-flutter-sdk.sh -c ${{ inputs.channel }} -p "${{ inputs.precache }}"
      shell: bash